##
# Auto include typoscript configuration
#
Neos:
  Neos:
    nodeTypes:
      groups:
        news:
          position: 'end'
          label: 'News'
    fusion:
      autoInclude:
        'Gmedia.News': TRUE

  Fusion:
    defaultContext:
      NewsConfiguration: 'Gmedia\News\TypoScript\Eel\Helper\ConfigurationHelper'

##
# The configuration for news plugin
#
Gmedia:
  News:
    view:
      list:
        pagination:
          itemsPerPage: 10
          maximumNumberOfLinks: 15
        sortProperty: 'dateTime'
        sortOrder: 'DESC'
        dateFormat: 'd M Y'
        thumbnailMaxWidth: 80
        thumbnailMaxHeight: 80
      latest:
        numberOfItems: 10
        pagination:
          itemsPerPage: 5
          maximumNumberOfLinks: 5
        sortProperty: 'dateTime'
        sortOrder: 'DESC'
        dateFormat: 'd. F Y'
        thumbnailMaxWidth: 80
        thumbnailMaxHeight: 80
      single:
        dateFormat: 'd. F Y'

