##
# Auto include typoscript configuration
#
Neos:
  Neos:
    nodeTypes:
      groups:
        news:
          position: 'end'
          label: 'News'
    fusion:
      autoInclude:
        'Gmedia.News': TRUE

  Fusion:
    defaultContext:
      NewsConfiguration: 'Gmedia\News\Fusion\Eel\Helper\ConfigurationHelper'

##
# The configuration for news plugin
#
Gmedia:
  News:
    renderer:
      metaTags: 'Gmedia.News:Components.MetaTags'
      archiveMenu: 'Gmedia.News:Components.ArchiveMenu'
      categoryMenu: 'Gmedia.News:Components.CategoryMenu'
      latest: 'Gmedia.News:Components.Latest'
      latestItem: 'Gmedia.News:Components.LatestItem'
      list: 'Gmedia.News:Components.List'
      listItem: 'Gmedia.News:Components.ListItem'
    view:
      list:
        pagination:
          itemsPerPage: 1
          maximumNumberOfLinks: 15
        sortProperty: 'dateTime'
        sortOrder: 'DESC'
        dateFormat: 'd. F Y'
        thumbnailMaxWidth: 300
        thumbnailMaxHeight: 200
        textSelector: '[instanceof Neos.NodeTypes:Text],[instanceof Neos.NodeTypes:TextWithImage]'
        imageSelector: '[instanceof Neos.NodeTypes:Image],[instanceof Neos.NodeTypes:TextWithImage]'
      latest:
        numberOfItems: 10
        pagination:
          itemsPerPage: 5
          maximumNumberOfLinks: 5
        sortProperty: 'dateTime'
        sortOrder: 'DESC'
        dateFormat: 'd. F Y'
        thumbnailMaxWidth: 80
        thumbnailMaxHeight: 80
        textSelector: '[instanceof Neos.NodeTypes:Text],[instanceof Neos.NodeTypes:TextWithImage]'
        imageSelector: '[instanceof Neos.NodeTypes:Image],[instanceof Neos.NodeTypes:TextWithImage]'
      single:
        dateFormat: 'd. F Y'

